### PR TITLE
Code consistency update

### PR DESCRIPTION
**Pull request by bdlukaa**
Made constructors `const` and updated documentation wherever possible.

### CODE REVIEW

**Comment by bdlukaa** [comment]
These tests are haunting me

**Comment by dshukertjr** [comment]
The testing thing is really weird 😂

BTW, I was thinking about using a more strict linting library like [very_good_analysis](https://pub.dev/packages/very_good_analysis), but what do you think about it? Maybe we can also introduce it in this PR and apply it to all the other libraries as well.

**Comment by dshukertjr** [comment]
@bdlukaa 
I think I was able to make the test work again (hopefully!). Could you try merging the main branch and run it thought again?

**Comment by bdlukaa** [comment]
@dshukertjr Tests seems to be now failing for something on the code. Tho, I don't have any warnings on my machine when running `dart analyze --fatal-warnings --fatal-infos .`

**Comment by dshukertjr** [comment]
@bdlukaa 
It seems like the lint error was from the constructor of `User` object. I added a comment to ignore the lint error, but please feel free to change it if there's a better way of handling it!

**Comment by dshukertjr** [comment]
Hmm, the same test failure consists...

**Comment by dshukertjr** [comment]
@phamhieu So sorry to ping you, but we might need your help again with fixing this test. The test passed with the same docker-compose file in [this](https://github.com/supabase/gotrue-dart/commit/5c798fbcc46c49a99e182205ef69c3e5fe8ca0e3) commit, but does not seem to work in this PR.

**Comment by phamhieu** [comment]
I will take a look. I'm not sure what is the problem also.

**Comment by bdlukaa** [comment]
#36

**Pull request closed without merging**
